model_config:
  model: UNet1 #the directory to which the results are saved
  initial_filter_size: [256]
  kernel: [3]
  drop_out_rate: [0.2]
  input_size: [128,1024]    #[1536, 1536] #h, w 
  channel: 1
  num_class: 9
  model_type: 'TransUnet' #multi_task, attention, fourier1, fourier1_2, single, TransUnet
  dropout: False
  anydepth: False
train_config:
  loss: dice_bce_mc
  accuracy: dice_bce_mc
  optimizer: SGD #SGD
  lr_rate: [0.01]
  weight_decay: [0]
  batch_size: [12]
  epochs: 100
  early_stop: 20
  num_workers: 20
  seed: 35
  use_cuda: True
dataset_config:
  train_path: ['/userfiles/cgunduz/datasets/retinal_layers/train']
  val_path: ['/userfiles/cgunduz/datasets/retinal_layers/val']
  test_path: ['/userfiles/cgunduz/datasets/retinal_layers/test']
  aug_rate: [0]
  save_dir: trans_retinallayers   #each experiment change here
  class_names: ['background','liver']
resume:
  flag: False
  path: workingtrans/models/last_epoch.pt
  epoch: 75

